# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloThere_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'NMapsMap'
pod 'naveridlogin-sdk-ios'
pod 'Alamofire'
pod 'KakaoSDKCommon'
pod 'KakaoSDKAuth'
pod 'KakaoSDKUser'
pod 'GoogleSignIn'
pod 'Firebase/Auth'
  # Pods for HelloThere_iOS

end
